### ISSUE TITLE
Allow to define custom description instead of hard coded one

### ISSUE THREAD

**Issue by butenkor** [commercetools/commercetools-paypal-plus-integration#132]
**Current behaviour**

It sends to PSP hard-coded payment [description](https://github.com/commercetools/commercetools-paypal-plus-integration/blob/master/src/main/java/com/commercetools/helper/mapper/impl/payment/BasePaymentMapperImpl.java#L139).

**Expected behaviour**

If optional field on payment custom type called `description` is defined than it should take it as description for PSP request. If field is not defined than as default it should use following text `Reference: ${payment.custom.fields.reference}`

**Comment by butenkor** [comment]
@andrii-kovalenko-ct Maybe [referenceText](https://github.com/commercetools/commercetools-paypal-plus-integration/search?utf8=%E2%9C%93&q=referenceText&type=) was meant for that as it is not used anywhere in code?

**Comment by andrii-kovalenko-ct** [comment]
@butenkor 
sounds reasonable.

Do we have any customers' requests and/or time request when it should be implemented/released?

**Comment by andrii-kovalenko-ct** [comment]
fixed by #137

**Comment by andrii-kovalenko-ct** [comment]
@pschwarzer @menzelcom 
https://github.com/commercetools/commercetools-paypal-plus-integration/releases/tag/v0.4.0
