### ISSUE TITLE
Re-factor APIContext generation in Paypal Plus payment service

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-paypal-plus-integration#27]
in [`PaypalPlusPaymentServiceImpl`](https://github.com/commercetools/commercetools-paypal-plus-integration/blob/dfe2f35b7febc947162ce0ff89f22fbf3c03e4a0/src/main/java/com/commercetools/service/paypalPlus/impl/PaypalPlusPaymentServiceImpl.java#L22-L22) the `APIContext` is injected once, but it can't be reused. For every PayPal request, one needs to specify new `requestId`. In SDK, `requestId` is created and cached in `com.paypal.base.rest.APIContext#getRequestId`. This method is then being called whenever a request to PayPal is made. Therefore, it's not possible to reuse `APIContext` in sequential requests!

- [ ] instead of injecting `APIContext` directly - create and inject `APIContextFactory` which will produce new `APIContext` instance for every new request.

**Comment by lojzatran** [comment]
Recommendation from Paypal Plus: https://github.com/paypal/PayPal-Java-SDK/wiki/Making-First-Call

**Comment by lojzatran** [comment]
To clarify, I created a question about this problem: https://github.com/paypal/PayPal-Java-SDK/issues/311
