### ISSUE TITLE
Paypal Plus taxes counting issue

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [commercetools/commercetools-paypal-plus-integration#28]
@butenkor @lojzatran 

We stumble upon one issue now. According to Paypal Plus doc:

> Please note:
> Including / excluding VAT
> To avoid rounding errors we recommend not submitting tax amounts on line item basis. Calculated tax amounts for the entire shopping basket may be submitted in the amount objects. In this case the item amounts will be treated as amounts excluding tax. In a B2C scenario, where taxes are included, no taxes should be submitted to PayPal.

This means, if we include shipping address to CTP cart (our normal case) the total price will be calculated with the taxes. The problem is that PayPal requires line items prices _excluding_ taxes!
There are 2 issues:
  1. we keep the prices including taxes in CTP line items, and the tax is calculated among whole cart
  2. We also apply discounts on line item basis.

So far we  could skip the _Details_ of the payment (exactly the part where shipping and taxes are specified) - this works on current test. Might be a problem in future with Invoice based payments.

What do you think about this?

**Comment by lojzatran** [comment]
Example of a wrong request:
cart:
```json
{
  "type": "Cart",
  "locale": "de",
  "lineItems": [
    {
      "productId": "xxx1",
      "variant": {
        "id": 1,
        "sku": "xxx1",
        "prices": [
          {
            "value": {
              "currencyCode": "EUR",
              "centAmount": 10000
            },
            "id": "9e812412-8d2b-484c-a987-d05c51d65d52"
          }
        ]
      },
      "price": {
        "value": {
          "currencyCode": "EUR",
          "centAmount": 10000
        },
        "id": "9e812412-8d2b-484c-a987-d05c51d65d52"
      },
      "quantity": 1,
      "taxRate": {
        "name": "19% MwSt",
        "amount": 0.19,
        "includedInPrice": true,
        "country": "DE",
        "id": "f9Exx3np",
        "subRates": []
      },
      "priceMode": "Platform",
      "totalPrice": {
        "currencyCode": "EUR",
        "centAmount": 10000
      },
      "taxedPrice": {
        "totalNet": {
          "currencyCode": "EUR",
          "centAmount": 8403
        },
        "totalGross": {
          "currencyCode": "EUR",
          "centAmount": 10000
        }
      }
    }
  ],
  "totalPrice": {
    "currencyCode": "EUR",
    "centAmount": 10000
  },
  "taxedPrice": {
    "totalNet": {
      "currencyCode": "EUR",
      "centAmount": 8403
    },
    "totalGross": {
      "currencyCode": "EUR",
      "centAmount": 10000
    },
    "taxPortions": [
      {
        "rate": 0.19,
        "amount": {
          "currencyCode": "EUR",
          "centAmount": 1597
        },
        "name": "19% MwSt"
      }
    ]
  },
  "country": "DE",
  "shippingAddress": {
    "salutation": "mr",
    "firstName": "Marc",
    "lastName": " Tester",
    "streetName": "Teststr.",
    "streetNumber": "30",
    "postalCode": "11111",
    "city": "Testcity",
    "country": "DE",
    "phone": "0123456789",
    "email": "test@test.de",
    "additionalAddressInfo": ""
  },
  "inventoryMode": "None",
  "taxMode": "Platform",
  "taxRoundingMode": "HalfEven"
}
```

PayPal request:
```json
{
  "transactions": [
    {
      "amount": {
        "currency": "EUR",
        "total": "100.00",
        "details": {
          "subtotal": "84.03",
          "shipping": "0.00",
          "tax": "15.97"
        }
      },
      "item_list": {
        "items": [
          {
            "sku": "xxx",
            "name": "xxx",
            "quantity": "1",
            "price": "100.00",
            "currency": "EUR"
          }
        ]
      }
    }
  ]
}
```

The problem is subtotal in PayPal request must add up to all items total and subtotal + shipping + tax = total.

**Comment by lojzatran** [comment]
After discussion with Roman and Florian, we decided not to include the tax in the details and `subtotal = total - shipping`. We have B2C case and according to the docs: `In a B2C scenario, where taxes are included, no taxes should be submitted to PayPal.`. For B2B case, there is already a task created (not so important): https://github.com/commercetools/commercetools-paypal-plus-integration/issues/42
