### ISSUE TITLE
On app start check for type and create if missing

### ISSUE THREAD

**Issue by lojzatran** [commercetools/commercetools-paypal-plus-integration#40]
Add automated builder on service run which verifies the required custom types exists and have proper custom fields/types

- if the custom type/filed does not exists - create one
- if a custom filed with the same name has different type - throw/log an exception and shut down the service

see also #4

**Comment by andrii-kovalenko-ct** [comment]
@lojzatran @butenkor @floriansattler
What should be do with complex type synchronization? I.e.:
[`EnumType`](http://dev.commercetools.com/http-api-projects-types.html#enumtype)/[`LocalizedEnum`](http://dev.commercetools.com/http-api-projects-types.html#localizedenumtype) - if some `values` are missing?
  - [ ] ignore (actually, current service implementation does not use values from the enums, it transparently sends them to PayPal Plus API)
  - [ ] log error message and exit service
  - ~add missing values~ (can't be done using regular CTP API)

[`ReferenceType`](http://dev.commercetools.com/http-api-projects-types.html#referencetype) - if `referenceTypeId` (string) is mismatched?
  - [ ] log error message and exit service
  - ~changing existing reference types are not allowed~

[`SetType`](http://dev.commercetools.com/http-api-projects-types.html#settype) - if `elementType` is mismatched?
  - [ ] log error message and exit service
  - ~changing existing element type is not allowed~

So, looks like in the best case we could only log such issues and propose the project owners manually sync the type, correct?

**Comment by lojzatran** [comment]
Then we should try to avoid using these complex types? Otherwise your suggestion is good, I think it would be too much work to try to implement the correct type syncer.

**Comment by andrii-kovalenko-ct** [comment]
At least `Enum` type is already used in #98 feature

**Comment by lojzatran** [comment]
Yes, that's why I want to say we should try to avoid and maybe use String :)

**Comment by butenkor** [comment]
> EnumType/LocalizedEnum - if some values are missing?

According to API Doc you can add new enum/lenum to existing custom field: https://dev.commercetools.com/http-api-projects-types.html#add-enumvalue-to-fielddefinition

> ReferenceType - if referenceTypeId (string) is mismatched?

log error message and exit service seems like a good choice 

> SetType - if elementType is mismatched?

Where do you use `set` type?

**Comment by andrii-kovalenko-ct** [comment]
>According to API Doc you can add new enum/lenum to existing custom field: https://dev.commercetools.com/http-api-projects-types.html#add-enumvalue-to-fielddefinition

oh, should we implement it? (not so easy because now we only add new types/ add new field definitions)

> `Where do you use set type?`

so far - nowhere, but if in the future we use - we won't recall we have to re-factor types synchronization. For example, Enums synchronizations task (from #98) came simultaneously with this "types synchronization" task, and if we don't have them at the same time - we would definitely forget it. 

But with `Set` it is  easy. Looks like "sync enum" requires extending the sync feature....

**Comment by andrii-kovalenko-ct** [comment]
@butenkor @lojzatran @floriansattler

Added enums/lenums sync. Set and Reference types divergence will cause error message.

11b95f8

**Comment by andrii-kovalenko-ct** [comment]
closed by https://github.com/commercetools/commercetools-paypal-plus-integration/pull/107

**Comment by andrii-kovalenko-ct** [comment]
https://github.com/commercetools/commercetools-paypal-plus-integration/pull/107
