### ISSUE TITLE
Use sphereClient.executeBlocking instead of join()

### ISSUE THREAD

**Issue by lojzatran** [commercetools/commercetools-paypal-plus-integration#45]
According to the [JVM SDK](http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/meta/SphereClientTuningDocumentation.html#blocking-client), we should use `executeBlocking()` for synchronous code. Don't use `join()` 

See also #35

**Comment by butenkor** [comment]
Not just for CTP SDK but in general. Related: https://github.com/commercetools/commercetools-paypal-plus-integration/pull/36#discussion_r132710769

**Comment by andrii-kovalenko-ct** [comment]
closed by #66
