### ISSUE TITLE
Verify and fix 2 edge cases when processing payment

### ISSUE THREAD

**Issue by lojzatran** [commercetools/commercetools-paypal-plus-integration#62]
First case:
1) user inputs an address Berlin, Germany
2) he clicks on Continue and is redirected to Paypal payment page with this address.
3) In a different tab, the same user changes his address to Paris, France.
4) The user confirms the payment in the first tab
5) Paypal has the address of Berlin, but the shop will deliver the goods to Paris.

Second case:
1) user has cart with item1=10€
2) user is redirected to Paypal payment page
3) in a different tab, user changes his cart to e.g. item2=20€
4) user completes the payment in the first tab
5) paypal approves the payment for 10€, but the real total amount has changed to 20€

**Comment by lojzatran** [comment]
Provide a new lookUp endpoint, which needs to be called before execute payment. Frontend needs to compare the total amount and line items, if they are the same as in the current cart. If not, the new payment needs to be created and the payment flow is restarted.

**Comment by andrii-kovalenko-ct** [comment]
for second case:
could/should we perform such a verification on back-end, when _execute_ endpoint is called (before actual execute)? We could compare total amount of the payment [identified by `paypalPlusPaymentId` from successUrl) and total amount of payment's cart - fail the request if they are not equal.

But the another option: isn't it a front-end responsibility to verify the payment before _execute_?
