### ISSUE TITLE
Implement CTP to PaypalPlus payments/transactions mapping

### ISSUE THREAD

**Issue by floriansattler** [commercetools/commercetools-paypal-plus-integration#7]

**Comment by andrii-kovalenko-ct** [comment]
@butenkor @lojzatran  
WDYT:
should be use the same names as where applicable for CTP custom fields, like it is already in [Payone Integration Service](https://github.com/commercetools/commercetools-payone-integration)?

For instance, in _Payone_ there is a custom field `pseudocardpan`, which has the same meaning and usage as `creditCardToken` in _Paypal Plus_ service. Should we keep the custom filed `pseudocardpan` or create a new one `creditCardToken`?

**Comment by floriansattler** [comment]
I think we should stick to the naming convention of PayPal here, as other devs using this repo might not be familiar with PAYONE, so it will cause more confusion if it is mixed up.

**Comment by andrii-kovalenko-ct** [comment]
I have just found that we use not payone specific name for it:

https://github.com/commercetools/commercetools-payone-integration/blob/0c7ff3823e95168ef4487dca4bb600f621eebc14/service/src/main/java/com/commercetools/pspadapter/payone/mapping/CustomFieldKeys.java#L17-L17

```java
public static final String CARD_DATA_PLACEHOLDER_FIELD = "cardDataPlaceholder";
```

But Payone HTTP request argument is called `pseudocardpan`. The payone integration service maps the `cardDataPlaceholder` custom field to this value:

https://github.com/commercetools/commercetools-payone-integration/blob/836ec64cdeb4b7dbb0b68a2a1d27c52c12ec1a71/service/src/main/java/com/commercetools/pspadapter/payone/mapping/CreditCardRequestFactory.java#L48-L49

https://github.com/commercetools/commercetools-payone-integration/blob/646d1bd9493650934401a47561f55754faa306cd/service/src/main/java/com/commercetools/pspadapter/payone/domain/payone/model/creditcard/CreditCardAuthorizationRequest.java#L21-L21

```java
final String pseudocardpan = ctPayment.getCustom().getFieldAsString(CustomFieldKeys.CARD_DATA_PLACEHOLDER_FIELD);
        CreditCardAuthorizationRequest request = new CreditCardAuthorizationRequest(getPayoneConfig(), pseudocardpan);

.......
//CreditCardAuthorizationRequest.java
public String getPseudocardpan() { return pseudocardpan;}
```

So, guess, we could stick with common CTP name `cardDataPlaceholder`, which every specific PSP integration service will map as they want.

**Comment by lojzatran** [comment]
Let's stick to the names that PayPal returns as Florian suggested.

**Comment by andrii-kovalenko-ct** [comment]
starting from [this commit](https://github.com/commercetools/commercetools-paypal-plus-integration/commit/72cb83f687aea7e6135bc57ea40c98f20007e54b#diff-c0b3871c6569bf6a25d3979e5904b28cR14) we are using where applicable **common commercetools names** (e.g., same as we use in [Payone Integration Service](https://github.com/commercetools/commercetools-payone-integration)
