### ISSUE TITLE
Gradle coloured output

### ISSUE THREAD

**Issue by Opalo** [commercetools/commercetools-paypal-plus-integration#97]
Hi,

I'm the guy that was talking about gradle in Munich last Wednesday. One of you asked me about colouring the output in gradle. What was the problem exactly? Sorry for starting new issue - obviously this is not how should I contact you, but have no other contact possibility, forgive me!

Actually I've this piece of code which works on Jenkins (ANSI plugin must be installed) and in console:

```
ext {
  YELLOW = '\033[93m'
  END = '\033[0m'
  GREEN = '\033[92m'
  BLUE = '\033[94m'
}

String color(String color, String str) {
  "${color}${str}${END}"
}

Closure<String> yellow = this.&color.curry(YELLOW)
Closure<String> green = this.&color.curry(GREEN)
Closure<String> blue = this.&color.curry(BLUE)

println(yellow('lol'))
println(green('lol'))
println(blue('lol'))
logger.lifecycle(yellow('lol'))
logger.lifecycle(green('lol'))
logger.lifecycle(blue('lol'))
```

**Comment by Opalo** [comment]
There was also second question about stopping the build after the very first test fails. It's not yet supported by gradle. The discussion starts [here](https://discuss.gradle.org/t/stop-test-build-execution-on-first-failure-and-flag-build-as-failed/4346), continues [here](https://issues.gradle.org/browse/GRADLE-1518) and is finally tracked [here](https://github.com/gradle/gradle/issues/1310).

**Comment by andrii-kovalenko-ct** [comment]
Thanks a lot @Opalo for taking back!

as for coloring output: this is almost the same approach we are using in this branch:
https://github.com/commercetools/commercetools-paypal-plus-integration/blob/test-travis-color-output/ColoredOutput.gradle
Though it is still a workaround. Maybe it is a good time to create a gradle plugin, or make a feature request? WDYT? Do you know any other discussions about this?

And special thanks for the set of discussions you provided about "fail fast task".

Hope to see you soon on the next gradle meetups!

**Comment by Opalo** [comment]
It will be difficult to see me soon, since I'm back to Warsaw, however thanks for the good word 😉 

When it comes to coloured output there're no other resources that I'm aware of. Implementing a plugin seems to be a good idea however I'd first rise an issue on gradle's github to verify the status.

**Comment by andrii-kovalenko-ct** [comment]
@Opalo 
https://github.com/radarsh/gradle-test-logger-plugin/
